### ISSUE TITLE
Support encryption at rest

### ISSUE THREAD

**Issue by rock59** [apache/incubator-kvrocks#143]
It would be nice to support encryption at rest. CockroachDB's implementation for Rocksdb maybe a good starting point.

**Comment by git-hulk** [comment]
it’s really a good point to enhance the security by encrypting the data node. I would have a look at how can we achieve it on the kvrocks.

**Comment by tisonkun** [comment]
Closed as inactive. We don't hold a wishing list. A proposal with design is welcome. Also, IIRC crdb drops the dependency to RocksDB and develops their own storage engine Pebble :)
