### ISSUE TITLE
Plan to RocksDB.GetProperty(prop)?

### ISSUE THREAD

**Issue by aniruddhadas** [apache/incubator-kvrocks#96]
Hi,

Is there are plan to expose the data in: rokuDB.getProperty("rocksdb.stats") in the near future?

Thanks
Aniruddha

**Comment by git-hulk** [comment]
@aniruddhadas the info command supported `info rocksdb` now

**Comment by aniruddhadas** [comment]
thanks @git-hulk. I wanted something more along the lines of:

`rocksDB.getProperty("rocksdb.stats");`

in Rocks DB the output is something like this:

** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      1/0   27.67 MB   0.2      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
  L1      6/0   250.68 MB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
  L2     59/0    2.47 GB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
  L3    450/0   24.96 GB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
  L4    983/0   61.31 GB   0.2      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
 Sum   1499/0   89.01 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0

** Compaction Stats [default] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Uptime(secs): 11824.1 total, 420.1 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

** File Read Latency Histogram By Level [default] **
** Level 0 read latency histogram (micros):
Count: 595411 Average: 4.8964  StdDev: 1.71
Min: 2  Median: 4.7328  Max: 82
Percentiles: P50: 4.73 P75: 5.40 P99: 8.78 P99.9: 31.12 P99.99: 46.36
------------------------------------------------------
(       1,       2 ]    29242   4.911%   4.911% #
(       2,       3 ]    35844   6.020%  10.931% #
(       3,       4 ]    68768  11.550%  22.481% ##
(       4,       6 ]   447222  75.111%  97.592% ###############
(       6,      10 ]    12077   2.028%  99.621% 
(      10,      15 ]      128   0.021%  99.642% 
(      15,      22 ]      170   0.029%  99.671% 
(      22,      34 ]     1795   0.301%  99.972% 
(      34,      51 ]      145   0.024%  99.997% 
(      51,      76 ]        9   0.002%  99.998% 
(      76,     110 ]        4   0.001%  99.999% 

** Level 1 read latency histogram (micros):
Count: 155861 Average: 4.5650  StdDev: 18.48
Min: 2  Median: 3.7945  Max: 7201
Percentiles: P50: 3.79 P75: 4.77 P99: 8.60 P99.9: 30.93 P99.99: 45.19
------------------------------------------------------
(       1,       2 ]     1102   0.707%   0.707% 
(       2,       3 ]    11512   7.386%   8.093% #
(       3,       4 ]    82212  52.747%  60.840% ###########
(       4,       6 ]    57697  37.018%  97.858% #######
(       6,      10 ]     2734   1.754%  99.612% 
(      10,      15 ]       32   0.021%  99.633% 
(      15,      22 ]       68   0.044%  99.677% 
(      22,      34 ]      468   0.300%  99.977% 
(      34,      51 ]       31   0.020%  99.997% 
(      51,      76 ]        1   0.001%  99.997% 
(      76,     110 ]        1   0.001%  99.998% 
(     170,     250 ]        1   0.001%  99.999% 
(     870,    1300 ]        1   0.001%  99.999% 
(    6600,    9900 ]        1   0.001% 100.000% 

** Level 2 read latency histogram (micros):
Count: 261055 Average: 6.1457  StdDev: 204.06
Min: 2  Median: 3.9624  Max: 48159
Percentiles: P50: 3.96 P75: 5.02 P99: 8.92 P99.9: 31.34 P99.99: 207.89
------------------------------------------------------
(       1,       2 ]     2065   0.791%   0.791% 
(       2,       3 ]    18478   7.078%   7.869% #
(       3,       4 ]   114276  43.775%  51.644% #########
(       4,       6 ]   119207  45.664%  97.307% #########
(       6,      10 ]     6046   2.316%  99.623% 
(      10,      15 ]       53   0.020%  99.644% 
(      15,      22 ]       90   0.034%  99.678% 
(      22,      34 ]      744   0.285%  99.963% 
(      34,      51 ]       46   0.018%  99.981% 
(      51,      76 ]       17   0.007%  99.987% 
(      76,     110 ]        4   0.002%  99.989% 
(     110,     170 ]        1   0.000%  99.989% 
(     170,     250 ]        4   0.002%  99.991% 
(     380,     580 ]        1   0.000%  99.991% 
(     580,     870 ]        1   0.000%  99.992% 
(     870,    1300 ]        1   0.000%  99.992% 
(    1300,    1900 ]        1   0.000%  99.992% 
(    1900,    2900 ]        1   0.000%  99.993% 
(    4400,    6600 ]        1   0.000%  99.993% 
(    6600,    9900 ]        2   0.001%  99.994% 
(    9900,   14000 ]        6   0.002%  99.996% 
(   14000,   22000 ]        2   0.001%  99.997% 
(   22000,   33000 ]        5   0.002%  99.999% 
(   33000,   50000 ]        3   0.001% 100.000% 

** Level 3 read latency histogram (micros):
Count: 342934 Average: 7.0989  StdDev: 247.84
Min: 2  Median: 4.1621  Max: 54037
Percentiles: P50: 4.16 P75: 5.15 P99: 9.28 P99.9: 61.18 P99.99: 6988.63
------------------------------------------------------
(       1,       2 ]     2368   0.691%   0.691% 
(       2,       3 ]    21750   6.342%   7.033% #
(       3,       4 ]   133214  38.845%  45.878% ########
(       4,       6 ]   174400  50.855%  96.733% ##########
(       6,      10 ]     9485   2.766%  99.499% #
(      10,      15 ]       61   0.018%  99.517% 
(      15,      22 ]      104   0.030%  99.547% 
(      22,      34 ]     1056   0.308%  99.855% 
(      34,      51 ]       94   0.027%  99.883% 
(      51,      76 ]      145   0.042%  99.925% 
(      76,     110 ]      154   0.045%  99.970% 
(     110,     170 ]       17   0.005%  99.975% 
(     170,     250 ]       33   0.010%  99.985% 
(     250,     380 ]        2   0.001%  99.985% 
(     380,     580 ]        2   0.001%  99.986% 
(     580,     870 ]        6   0.002%  99.987% 
(     870,    1300 ]        1   0.000%  99.988% 
(    1300,    1900 ]        2   0.001%  99.988% 
(    1900,    2900 ]        1   0.000%  99.989% 
(    2900,    4400 ]        3   0.001%  99.990% 
(    4400,    6600 ]        1   0.000%  99.990% 
(    6600,    9900 ]        6   0.002%  99.992% 
(    9900,   14000 ]        4   0.001%  99.993% 
(   14000,   22000 ]       10   0.003%  99.996% 
(   22000,   33000 ]        9   0.003%  99.998% 
(   33000,   50000 ]        5   0.001% 100.000% 
(   50000,   75000 ]        1   0.000% 100.000% 

** Level 4 read latency histogram (micros):
Count: 512264 Average: 5.6432  StdDev: 170.13
Min: 2  Median: 3.7920  Max: 76929
Percentiles: P50: 3.79 P75: 4.75 P99: 7.94 P99.9: 91.25 P99.99: 961.74
------------------------------------------------------
(       1,       2 ]     4421   0.863%   0.863% 
(       2,       3 ]    38240   7.465%   8.328% #
(       3,       4 ]   269526  52.615%  60.943% ###########
(       4,       6 ]   192558  37.590%  98.532% ########
(       6,      10 ]     4951   0.966%  99.499% 
(      10,      15 ]       60   0.012%  99.510% 
(      15,      22 ]       88   0.017%  99.528% 
(      22,      34 ]     1306   0.255%  99.783% 
(      34,      51 ]      102   0.020%  99.802% 
(      51,      76 ]      227   0.044%  99.847% 
(      76,     110 ]      608   0.119%  99.965% 
(     110,     170 ]       33   0.006%  99.972% 
(     170,     250 ]       68   0.013%  99.985% 
(     250,     380 ]        8   0.002%  99.987% 
(     380,     580 ]        9   0.002%  99.988% 
(     580,     870 ]        5   0.001%  99.989% 
(     870,    1300 ]       13   0.003%  99.992% 
(    1300,    1900 ]        4   0.001%  99.993% 
(    1900,    2900 ]        3   0.001%  99.993% 
(    2900,    4400 ]        8   0.002%  99.995% 
(    4400,    6600 ]        5   0.001%  99.996% 
(    6600,    9900 ]        6   0.001%  99.997% 
(    9900,   14000 ]        5   0.001%  99.998% 
(   14000,   22000 ]        3   0.001%  99.999% 
(   22000,   33000 ]        4   0.001%  99.999% 
(   33000,   50000 ]        2   0.000% 100.000% 
(   75000,  110000 ]        1   0.000% 100.000% 


** DB Stats **
Uptime(secs): 11824.1 total, 420.1 interval
Cumulative writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 GB, 0.00 MB/s
Cumulative WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Cumulative stall: 00:00:0.000 H:M:S, 0.0 percent
Interval writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Interval stall: 00:00:0.000 H:M:S, 0.0 percent
...

**Comment by git-hulk** [comment]
Won't do it now, feel free to reopen or create a new one.
