### ISSUE TITLE
Any benchmark compare with ledis, ssdb or redix? simple test seems write performance much slower....

### ISSUE THREAD

**Issue by binwangcn** [apache/incubator-kvrocks#99]
**Describe the bug**

 - OS: [e.g. Centos 7]
 - Version [e.g. 1.1.5]

**To Reproduce**
1. 
2.
3.

**Expected behavior**

**Comment by git-hulk** [comment]
compare with Redis or others? can you paste the Redis benchmark log?

**Comment by tisonkun** [comment]
Closed as stale. I suppose you run [`redis-benchmark`](https://redis.io/docs/reference/optimization/benchmarks/) against these systems.

Looking forward to any feedback.
